### PR TITLE
I optimized the code, made it faster and more Pythonic

### PR DESCRIPTION
**Pull request by neu-ma-tic**
hello, i fixed some
			minor bugs in the program.
				i hope that
					my contribution
						is appreciated, and that
							these glaring issues no longer exist
								after my PR is merged.
									<3 [neumatic](https://neumatic.club)

### CODE REVIEW

**Comment by ghost** [comment]
image

**Comment by neu-ma-tic** [comment]
thank you for your input, @c6c534e825f4a3d41ede3e67473187d1

**Comment by dropalways** [comment]
nah bro what is this 😭 
i am NOT merging this + the readme is broken

**Comment by neu-ma-tic** [comment]
but .... butt.... it's not broken, it's improved!

**Comment by ghost** [comment]
if you think your code is improved, you must be severely autistic ngl

**Pull request closed without merging**
